### PR TITLE
feat(fake-auth): add callback event to fake auth handler

### PR DESCRIPTION
**Pull request by ToWe0815**
The PR adds a callback event to the fake auth handler to enable the user the manipulation of the created identity before its usage. 

A typical use case could be the creation of several mock "users", all having different claims/roles for testing purposes. These "users" are distinguished by having different fake ids, that are getting set via the "x-zitadel-fake-user-id" header when testing typical auth scenarios.

### CODE REVIEW

**Comment by buehler** [comment]
Hey @ToWe0815 
The tests /linting are failing

**Comment by ToWe0815** [comment]
Hey @buehler 
Should be fixed now!

**Comment by buehler** [comment]
Did you update to v6?
GitHub says there are merge conflicts

**Comment by ToWe0815** [comment]
Done, my bad.

**Comment by ToWe0815** [comment]
@buehler Is there anything I need to do for this change to be merged? Am I missing something?

**Comment by buehler** [comment]
Hey @ToWe0815 

Yes, please make sure that the tests are running. Otherwise, I cannot merge it.

**Comment by ToWe0815** [comment]
> Hey @ToWe0815
> 
> Yes, please make sure that the tests are running. Otherwise, I cannot merge it.

Hey @buehler 

As far as I can see the tests are failing because of a known vulnerability in the 'BouncyCastle.Cryptography' package:
`/home/runner/work/zitadel-net/zitadel-net/src/Zitadel/Zitadel.csproj : error NU1902: Warning As Error: Package 'BouncyCastle.Cryptography' 2.2.1 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-8xfc-gm6g-vgpv [/home/runner/work/zitadel-net/zitadel-net/Zitadel.sln]`

There are already 2 open PRs regarding this issue (among other similar things):
https://github.com/smartive/zitadel-net/pull/930
https://github.com/smartive/zitadel-net/pull/926

Semi-Off topic:
The whole project seems to be a bit shaky right now and I think you should take some time to look into open PRs & Issues.

`ServiceAccountTest.Should_Throw_With_Meaningful_Error()` fails locally on my machine, because the Token Endpoint of the project's Zitadel instance responds with a HTTP 500 when a meaningful error is expected by said test case. This might be due to a change on Zitadel's side and cannot come from my changes made in this PR, since I only added functionality to auth mocking.

Also `buf generate` doesn't seem to run automagically on build anymore:
https://github.com/smartive/zitadel-net/issues/925

I had to execute `buf generate` manually to make it work, but I'm also not deep enough into the topic to fix the problem's source.

**Comment by buehler** [comment]
Hey @ToWe0815 
Thanks to a PR, all the deps are updated. You should be able to fix the linting errors :)

**Pull request merged**
